
SOURCE = Percolation.java \
	PercolationStats.java

all: $(SOURCE)
	-@echo Building Percolation...
	javac-algs4 -Xlint Percolation.java

debug: $(COURSE)
	javac-algs4 -Xlint -g Torrganizer.java


clean:
	rm *.class

