
SOURCE = Deque.java \
	RandomizedQueue.java \
    Permutation.java

all: $(SOURCE)
	-@echo Building Deque...
	javac-algs4 -Xlint Deque.java
	javac-algs4 -Xlint RandomizedQueue.java
	javac-algs4 -Xlint Permutation.java

clean:
	rm *.class

